### ISSUE TITLE
'require': cannot load such file -- thor

### ISSUE THREAD

**Issue by ricardopereira** [unmix/unmix#2]
⚠️ I have no experience with ruby.

When I try to run `unmix`:

``` bash
➜  Unmix git:(master) ./unmix.rb youtube --input https://www.youtube.com/watch\?v\=5S8lKZ0MMUQ
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thor (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./unmix.rb:2:in `<main>'
```

Then I executed: `bundle install`:

``` bash
Installing awesome_print 1.2.0
Installing debug_inspector 0.0.2
Installing binding_of_caller 0.7.2
Installing coderay 1.1.0
Installing method_source 0.8.2
Installing paint 1.0.0
Installing slop 3.6.0
Installing pry 0.10.1
Installing pry-stack_explorer 0.4.9.1
Installing restclient 0.11.2
Installing table_print 1.5.3
Using bundler 1.9.2
Bundle complete! 5 Gemfile dependencies, 12 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

But then it gives me the same error message when I try to run `unmix`.

**Comment by ricardopereira** [comment]
My setup:

```
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

$ bundle -v
Bundler version 1.10.2

$ gem -v
2.4.7
```

**Comment by eladg** [comment]
Thanks @ricardopereira. Yes, it's still very experimental & buggy. I'm currently focusing on trying to check if the concept is possible.

Once this will be usable. I will make sure a proper installation is in place (say, `gem install unmix`, then just calling `unmix` from command line).
